In [3]:
import tensorflow as tf
import numpy as np

## Save to file
# remember to define the same dtype and shape when restore
W = tf.Variable([[1,2,3],[3,4,5]], dtype=tf.float32, name='weights')
b = tf.Variable([[1,2,3]], dtype=tf.float32, name='biases')

# init= tf.initialize_all_variables() # tf 马上就要废弃这种写法
# 替换成下面的写法:
init = tf.global_variables_initializer()

In [9]:
# remember to define the same dtype and shape whem there
saver=tf.train.Saver()

with tf.Session() as sess:
    sess.run(init)
    save_path=saver.save(sess,"/home/piker/Desktop/save_net.ckpt")
    print(save_path)

/home/piker/Desktop/save_net.ckpt


In [3]:
import tensorflow as tf
import numpy as np

In [8]:
# retore variables
# redfine
W = tf.Variable(np.arange(6).reshape((2,3)),dtype=tf.float32,name='weights')
b = tf.Variable(np.arange(3).reshape((1, 3)), dtype=tf.float32, name='biases')

saver=tf.train.Saver()
with tf.Session() as sess:
    saver.restore(sess,"/home/piker/Desktop/save_net.ckpt")
    print(sess.run(W))
    print(sess.run(b))


INFO:tensorflow:Restoring parameters from /home/piker/Desktop/save_net.ckpt
[[1. 2. 3.]
 [3. 4. 5.]]
[[1. 2. 3.]]


In [ ]:
# saver 保存只能保存变量，不能保存框架！！！
# retore 还要再训练一遍# 学习链接：莫凡pytho https://morvanzhou.github.io/tutorials/machine-learning/tensorflow/5-06-save/